# Generated by Django 5.2.17 on 2026-08-13 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('template_key', models.CharField(max_length=60)),
                ('template_version', models.CharField(default='v1', max_length=20)),
                ('template_data', models.JSONField(default=dict)),
                ('related_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('sent', 'Sent'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_category', models.CharField(blank=True, max_length=60)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='communicati_state_a741e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_email', models.BooleanField(default=True)),
                ('queue_email', models.BooleanField(default=True)),
                ('in_app', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=500)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='communicati_user_id_92b2a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=20)),
                ('safe_error_category', models.CharField(blank=True, max_length=60)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='communications.notificationoutbox')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('outbox', 'attempt_number'), name='unique_outbox_attempt')],
            },
        ),
    ]
