# Generated by Django 5.2.17 on 2026-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='appointment_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='queue_email',
            field=models.BooleanField(default=False),
        ),
    ]
