# Generated by Django 5.2.17 on 2026-08-13 22:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('patient', 'Patient'), ('reception', 'Reception'), ('walk_in', 'Walk in')], max_length=16)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], default='confirmed', max_length=16)),
                ('booking_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.chamber')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.hospital')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='directory.patientprofile')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='operations.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('state', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid_on_site', 'Paid on site'), ('waived', 'Waived'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('collection_channel', models.CharField(blank=True, max_length=30)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='operations.appointment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('previous_state', models.CharField(blank=True, max_length=20)),
                ('new_state', models.CharField(max_length=20)),
                ('previous_amount_minor', models.PositiveIntegerField(null=True)),
                ('new_amount_minor', models.PositiveIntegerField()),
                ('request_id', models.UUIDField(db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='operations.paymentrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=12)),
                ('next_token_sequence', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('last_material_event_at', models.DateTimeField(blank=True, null=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_sessions', to='directory.chamber')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_sessions', to='directory.doctorprofile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_sessions', to='directory.location')),
            ],
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=20)),
                ('token_sequence', models.PositiveIntegerField()),
                ('checked_in_at', models.DateTimeField()),
                ('effective_waiting_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In service'), ('deferred', 'Deferred'), ('completed', 'Completed'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='waiting', max_length=16)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_ended_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('last_transition_at', models.DateTimeField()),
                ('service_sample_valid', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='queue_ticket', to='operations.appointment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='operations.queuesession')),
            ],
            options={
                'ordering': ['effective_waiting_at', 'token_sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='queuesession',
            name='active_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_sessions', to='operations.queueticket'),
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(max_length=20)),
                ('previous_state', models.CharField(blank=True, max_length=16)),
                ('new_state', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('request_id', models.UUIDField(db_index=True)),
                ('revision_before', models.PositiveBigIntegerField()),
                ('revision_after', models.PositiveBigIntegerField()),
                ('ordering_facts', models.JSONField(default=dict)),
                ('followed_fifo', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.queuesession')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.queueticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEstimateRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(default='aaw_v1', max_length=20)),
                ('sample_digest', models.CharField(max_length=64)),
                ('sample_count', models.PositiveSmallIntegerField()),
                ('configured_duration', models.DecimalField(decimal_places=3, max_digits=7)),
                ('observed_median', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('observed_mad', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('observed_spread', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('service_estimate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('active_state', models.CharField(blank=True, max_length=16)),
                ('elapsed_minutes', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('active_remaining_minutes', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('people_ahead', models.PositiveIntegerField(default=0)),
                ('point_wait_minutes', models.PositiveIntegerField(null=True)),
                ('uncertainty_minutes', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('wait_lower_minutes', models.PositiveIntegerField(null=True)),
                ('wait_upper_minutes', models.PositiveIntegerField(null=True)),
                ('confidence', models.CharField(max_length=12)),
                ('safety_buffer_minutes', models.PositiveSmallIntegerField()),
                ('return_window_start', models.DateTimeField(null=True)),
                ('return_window_end', models.DateTimeField(null=True)),
                ('queue_revision', models.PositiveBigIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='operations.queuesession')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='operations.queueticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_local', models.TimeField()),
                ('end_local', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('capacity_per_slot', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='directory.chamber')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='directory.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='directory.hospital')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='directory.location')),
            ],
            options={
                'ordering': ['doctor', 'weekday', 'start_local'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='operations.schedule'),
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('kind', models.CharField(choices=[('closed', 'Closed'), ('replacement', 'Replacement')], max_length=16)),
                ('start_local', models.TimeField(blank=True, null=True)),
                ('end_local', models.TimeField(blank=True, null=True)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('capacity_per_slot', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reason', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='operations.schedule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.UniqueConstraint(fields=('session', 'token'), name='unique_queue_token'),
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.UniqueConstraint(fields=('session', 'token_sequence'), name='unique_queue_sequence'),
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['called', 'in_service'])), fields=('session',), name='one_active_queue_ticket'),
        ),
        migrations.AddConstraint(
            model_name='queuesession',
            constraint=models.UniqueConstraint(fields=('doctor', 'location', 'chamber', 'service_date'), name='unique_queue_session'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_local__gt', models.F('start_local'))), name='schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='schedule_valid_dates'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['schedule', 'start_at', 'status'], name='operations__schedul_f02ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'start_at'], name='operations__patient_7d0fc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('schedule', 'service_date'), name='unique_schedule_exception_date'),
        ),
    ]
