# Generated by Django 5.2.17 on 2026-08-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='late_by_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='was_late',
            field=models.BooleanField(default=False),
        ),
    ]
