# Generated by Django 5.2.17 on 2026-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_appointment_deduplication_and_append_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='new_collection_channel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='new_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='previous_collection_channel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='previous_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
