# Generated by Django 5.2.17 on 2026-08-13 22:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=180)),
                ('short_name', models.CharField(max_length=80)),
                ('logo_url', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use an E.164 phone number.')])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('operational_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MRNSequence',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='mrn_sequence', serialize=False, to='directory.hospital')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='directory.hospital')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use an E.164 phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='directory.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambers', to='directory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mrn', models.CharField(editable=False, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use an E.164 phone number.')])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=16)),
                ('address', models.CharField(max_length=500)),
                ('is_claimed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='directory.hospital')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyNoticeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('effective_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_notices', to='directory.hospital')),
            ],
            options={
                'ordering': ['-effective_at'],
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='active_privacy_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_hospitals', to='directory.privacynoticeversion'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=100)),
                ('decision', models.BooleanField()),
                ('channel', models.CharField(choices=[('self_service', 'Self service'), ('assisted', 'Assisted')], max_length=20)),
                ('request_id', models.UUIDField(db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='directory.patientprofile')),
                ('notice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='directory.privacynoticeversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_code', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=160)),
                ('designation', models.CharField(max_length=160)),
                ('registration_reference', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('consultation_fee_minor', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('departments', models.ManyToManyField(related_name='doctors', to='directory.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='directory.hospital')),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'doctor_code'), name='unique_doctor_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_department_name'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_location_name'),
        ),
        migrations.AddConstraint(
            model_name='chamber',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_chamber_name'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['hospital', 'phone'], name='directory_p_hospita_34c7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['hospital', 'email'], name='directory_p_hospita_c9f831_idx'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticeversion',
            constraint=models.UniqueConstraint(fields=('hospital', 'version'), name='unique_privacy_notice_version'),
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_hospital'),
        ),
    ]
