# Generated by Django 5.2.17 on 2026-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, default='MAIN', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_location_code'),
        ),
    ]
