# Generated by Django 5.2.17 on 2026-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_patient_correction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='tagline',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='registration_source',
            field=models.CharField(choices=[('self_service', 'Self service'), ('reception', 'Reception')], default='self_service', max_length=20),
        ),
    ]
