# Generated by Django 5.2.17 on 2026-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_hospital_tagline_patientprofile_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
