# Generated by Django 5.2.17 on 2026-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_hospital_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='short_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(default='MAIN', max_length=12),
        ),
    ]
